[unix_http_server]
file=__home__/.local/supervisor/supervisor.sock

[supervisord]
logfile=__home__/.local/supervisor/supervisord.log
pidfile=__home__/.local/supervisor/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://__home__/.local/supervisor/supervisor.sock

[include]
files = __home__/.config/supervisor.d/*.ini
